#!/bin/sh
#set -x 
if [ $# -ne 2 ]
then
    echo please make sure argc=2
	exit
fi

sour=./$1
dest=./$2

if [ -d ./$1 ]
then
    echo you will cp $1 to $2
else
    echo $1 not exit
    exit
fi

if [ -d ./$2 ]
then
    echo $2 exit you cani\'t cp
    exit
fi

cp -a $1 $2

rm ./$2/$1
mv ./$2/$1.c ./$2/$2.c

sed -i 's/'$1'/'$2'/g' ./$2/$2.c
sed -i 's/'$1'/'$2'/g' ./$2/Makefile

echo cp done
